# Generated by Django 3.0.7 on 2020-11-15 23:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('stock_id', models.IntegerField()),
                ('ticker', models.CharField(max_length=100)),
                ('add_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
