# Generated by Django 3.0.7 on 2020-11-15 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investorprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='stock_id',
        ),
    ]
