# Generated by Django 3.0.7 on 2020-09-27 17:26

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Francois',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('designation', models.CharField(max_length=300)),
                ('about_para1', ckeditor.fields.RichTextField()),
                ('about_me_side_bar', ckeditor.fields.RichTextField()),
                ('about_blockquote', ckeditor.fields.RichTextField()),
                ('about_short', ckeditor.fields.RichTextField()),
                ('facebook_link', models.URLField(blank=True, max_length=100)),
                ('twitter_link', models.URLField(blank=True, max_length=100)),
                ('instagram_link', models.URLField(blank=True, max_length=100)),
                ('last_update', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('home_images1', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('home_images2', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('home_images3', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('home_images4', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('home_images5', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('home_images6', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('home_images7', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('home_images8', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('about_side_bar', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
